# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Aug  8 04:44:05 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(531, 575)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 511, 511))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 15, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(122, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.tableView_2 = QtGui.QTableView(self.gridLayoutWidget)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.tableView_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_2.horizontalHeader().setDefaultSectionSize(98)
        self.tableView_2.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView_2, 4, 0, 1, 4)
        self.toolButton = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 3, 1, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 15, 1, 1, 1)
        self.tableView = QtGui.QTableView(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setDefaultSectionSize(106)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtGui.QSpacerItem(200, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 531, 25))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuManual = QtGui.QMenu(self.menuAyuda)
        self.menuManual.setObjectName(_fromUtf8("menuManual"))
        self.menuVariables = QtGui.QMenu(self.menuManual)
        self.menuVariables.setObjectName(_fromUtf8("menuVariables"))
        self.menuTipos = QtGui.QMenu(self.menuVariables)
        self.menuTipos.setObjectName(_fromUtf8("menuTipos"))
        self.menuArchivo = QtGui.QMenu(self.menuBar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionGeneralGeneral = QtGui.QAction(MainWindow)
        self.actionGeneralGeneral.setObjectName(_fromUtf8("actionGeneralGeneral"))
        self.actionEvaluaciones = QtGui.QAction(MainWindow)
        self.actionEvaluaciones.setObjectName(_fromUtf8("actionEvaluaciones"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionGeneralVariables = QtGui.QAction(MainWindow)
        self.actionGeneralVariables.setObjectName(_fromUtf8("actionGeneralVariables"))
        self.actionGeneralTipos = QtGui.QAction(MainWindow)
        self.actionGeneralTipos.setObjectName(_fromUtf8("actionGeneralTipos"))
        self.actionALGEBRAICA = QtGui.QAction(MainWindow)
        self.actionALGEBRAICA.setObjectName(_fromUtf8("actionALGEBRAICA"))
        self.actionPROMEDIO = QtGui.QAction(MainWindow)
        self.actionPROMEDIO.setObjectName(_fromUtf8("actionPROMEDIO"))
        self.actionCONDICIONAL = QtGui.QAction(MainWindow)
        self.actionCONDICIONAL.setObjectName(_fromUtf8("actionCONDICIONAL"))
        self.actionCargar = QtGui.QAction(MainWindow)
        self.actionCargar.setObjectName(_fromUtf8("actionCargar"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionGuardar_plantilla = QtGui.QAction(MainWindow)
        self.actionGuardar_plantilla.setObjectName(_fromUtf8("actionGuardar_plantilla"))
        self.actionNF = QtGui.QAction(MainWindow)
        self.actionNF.setObjectName(_fromUtf8("actionNF"))
        self.menuTipos.addAction(self.actionGeneralTipos)
        self.menuTipos.addSeparator()
        self.menuTipos.addAction(self.actionALGEBRAICA)
        self.menuTipos.addAction(self.actionPROMEDIO)
        self.menuTipos.addAction(self.actionCONDICIONAL)
        self.menuVariables.addAction(self.actionGeneralVariables)
        self.menuVariables.addSeparator()
        self.menuVariables.addAction(self.actionNF)
        self.menuVariables.addAction(self.menuTipos.menuAction())
        self.menuManual.addAction(self.actionGeneralGeneral)
        self.menuManual.addSeparator()
        self.menuManual.addAction(self.actionEvaluaciones)
        self.menuManual.addAction(self.menuVariables.menuAction())
        self.menuAyuda.addAction(self.menuManual.menuAction())
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAbout)
        self.menuArchivo.addAction(self.actionCargar)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_plantilla)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())
        self.mainToolBar.addAction(self.actionCargar)
        self.mainToolBar.addAction(self.actionGuardar)
        self.mainToolBar.addAction(self.actionGuardar_plantilla)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.tableView_2)
        MainWindow.setTabOrder(self.tableView_2, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.toolButton_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Promedieitor", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Agregar Evaluación", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Agregar Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body>\n"
"<h3>Evaluación</h3>\n"
"<ul>\n"
"<li>Nombre: Nombre o preferiblemente abreviación</li>\n"
"<li>Nota: Valor, entero o decimal de la Evaluación</li>\n"
"</ul>\n"
"Dos Evaluaciones no deben tener el mismo nombre, en el caso que así sea solo se considerara la primera dentro de los cálculos\n"
"</body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body>\n"
"<h3>Variable</h3>\n"
"<ul>\n"
"<li>Nombre: al igual que las evaluaciones se prefieren abreviaciones</li>\n"
"<li>Valor: es el valor que toman luego de ser procesadas</li>\n"
"<li>Tipo: { ALGEBRAICA|PROMEDIO|CONDICIONAL }</li>\n"
"<li>Parámetros: Click para mas informacion</li>\n"
"<li>Ponderación: Es el factor por el cual se multiplicara el resultado de la subrutina, obteniendo luego el valor final</li>\n"
"</ul>\n"
"<h4>Variable NF</h4>\n"
"<p>NF es una variable especial. aquí es donde llega el resultado final luego de ser procesado por Promedieitor\n"
"por lo que esta PROHIBIDO cambiar su nombre\n"
"</p>\n"
"</body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Promedio", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuManual.setTitle(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVariables.setTitle(QtGui.QApplication.translate("MainWindow", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTipos.setTitle(QtGui.QApplication.translate("MainWindow", "Tipos", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneralGeneral.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvaluaciones.setText(QtGui.QApplication.translate("MainWindow", "Evaluaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneralVariables.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneralTipos.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionALGEBRAICA.setText(QtGui.QApplication.translate("MainWindow", "ALGEBRAICA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPROMEDIO.setText(QtGui.QApplication.translate("MainWindow", "PROMEDIO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCONDICIONAL.setText(QtGui.QApplication.translate("MainWindow", "CONDICIONAL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCargar.setText(QtGui.QApplication.translate("MainWindow", "Abrir archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar_plantilla.setText(QtGui.QApplication.translate("MainWindow", "Guardar plantilla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNF.setText(QtGui.QApplication.translate("MainWindow", "NF", None, QtGui.QApplication.UnicodeUTF8))

