# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Aug  5 01:43:27 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(457, 556)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 441, 511))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 15, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(180, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(74, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.tableView_2 = QtGui.QTableView(self.gridLayoutWidget)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.tableView_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_2.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView_2, 4, 0, 1, 4)
        self.toolButton = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 3, 1, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout.addWidget(self.toolButton_2, 15, 1, 1, 1)
        self.tableView = QtGui.QTableView(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setDefaultSectionSize(105)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 457, 25))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuAbout = QtGui.QMenu(self.menuAyuda)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuVariables = QtGui.QMenu(self.menuAbout)
        self.menuVariables.setObjectName(_fromUtf8("menuVariables"))
        self.menuTipos = QtGui.QMenu(self.menuVariables)
        self.menuTipos.setObjectName(_fromUtf8("menuTipos"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionGeneral = QtGui.QAction(MainWindow)
        self.actionGeneral.setObjectName(_fromUtf8("actionGeneral"))
        self.actionGenera = QtGui.QAction(MainWindow)
        self.actionGenera.setObjectName(_fromUtf8("actionGenera"))
        self.actionEvaluaciones = QtGui.QAction(MainWindow)
        self.actionEvaluaciones.setObjectName(_fromUtf8("actionEvaluaciones"))
        self.actionGeneral_2 = QtGui.QAction(MainWindow)
        self.actionGeneral_2.setObjectName(_fromUtf8("actionGeneral_2"))
        self.actionEvaluaciones_2 = QtGui.QAction(MainWindow)
        self.actionEvaluaciones_2.setObjectName(_fromUtf8("actionEvaluaciones_2"))
        self.actionAbout_2 = QtGui.QAction(MainWindow)
        self.actionAbout_2.setObjectName(_fromUtf8("actionAbout_2"))
        self.actionGeneral_3 = QtGui.QAction(MainWindow)
        self.actionGeneral_3.setObjectName(_fromUtf8("actionGeneral_3"))
        self.actionPonderaci_n = QtGui.QAction(MainWindow)
        self.actionPonderaci_n.setObjectName(_fromUtf8("actionPonderaci_n"))
        self.actionGeneral_4 = QtGui.QAction(MainWindow)
        self.actionGeneral_4.setObjectName(_fromUtf8("actionGeneral_4"))
        self.actionCONSTANTE = QtGui.QAction(MainWindow)
        self.actionCONSTANTE.setObjectName(_fromUtf8("actionCONSTANTE"))
        self.actionSUMA = QtGui.QAction(MainWindow)
        self.actionSUMA.setObjectName(_fromUtf8("actionSUMA"))
        self.actionPRODUCTO = QtGui.QAction(MainWindow)
        self.actionPRODUCTO.setObjectName(_fromUtf8("actionPRODUCTO"))
        self.actionPROMEDIO = QtGui.QAction(MainWindow)
        self.actionPROMEDIO.setObjectName(_fromUtf8("actionPROMEDIO"))
        self.actionCONDICION = QtGui.QAction(MainWindow)
        self.actionCONDICION.setObjectName(_fromUtf8("actionCONDICION"))
        self.menuTipos.addAction(self.actionGeneral_4)
        self.menuTipos.addSeparator()
        self.menuTipos.addAction(self.actionCONSTANTE)
        self.menuTipos.addAction(self.actionSUMA)
        self.menuTipos.addAction(self.actionPRODUCTO)
        self.menuTipos.addAction(self.actionPROMEDIO)
        self.menuTipos.addAction(self.actionCONDICION)
        self.menuVariables.addAction(self.actionGeneral_3)
        self.menuVariables.addSeparator()
        self.menuVariables.addAction(self.actionPonderaci_n)
        self.menuVariables.addAction(self.menuTipos.menuAction())
        self.menuAbout.addAction(self.actionGeneral_2)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionEvaluaciones_2)
        self.menuAbout.addAction(self.menuVariables.menuAction())
        self.menuAyuda.addAction(self.menuAbout.menuAction())
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAbout_2)
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Promedieitor", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Agregar Evaluación", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Agregar Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Promedio", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>No olvidar EDITAR</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>No olvidar EDITAR</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVariables.setTitle(QtGui.QApplication.translate("MainWindow", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTipos.setTitle(QtGui.QApplication.translate("MainWindow", "Tipos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneral.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenera.setText(QtGui.QApplication.translate("MainWindow", "Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvaluaciones.setText(QtGui.QApplication.translate("MainWindow", "Evaluaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneral_2.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvaluaciones_2.setText(QtGui.QApplication.translate("MainWindow", "Evaluaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_2.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneral_3.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPonderaci_n.setText(QtGui.QApplication.translate("MainWindow", "Ponderación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneral_4.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCONSTANTE.setText(QtGui.QApplication.translate("MainWindow", "CONSTANTE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSUMA.setText(QtGui.QApplication.translate("MainWindow", "SUMA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPRODUCTO.setText(QtGui.QApplication.translate("MainWindow", "PRODUCTO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPROMEDIO.setText(QtGui.QApplication.translate("MainWindow", "PROMEDIO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCONDICION.setText(QtGui.QApplication.translate("MainWindow", "CONDICION", None, QtGui.QApplication.UnicodeUTF8))

